<?php namespace SaleBoss\Services\User;

use Illuminate\Support\Facades\Config;
use SaleBoss\Models\User;
use SaleBoss\Repositories\EntityRepositoryInterface;
use SaleBoss\Repositories\EntityTypeRepositoryInterface;
use SaleBoss\Repositories\OrderRepositoryInterface;
use SaleBoss\Repositories\StateRepositoryInterface;
use SaleBoss\Repositories\UserRepositoryInterface;
use SaleBoss\Services\EavSmartAss\EavManager;

class Dashboard implements DashboardInterface {

	protected $userRepo;
	protected $user;
	protected $stateRepo;
	protected $orderRepo;
	protected $userQueue;
	protected $typeRepo;
	protected $entityRepo;

	/**
	 * @TODO too much injection
	 *
	 * @param UserRepositoryInterface $userRepo
	 * @param EavManager $manager
	 * @param StateRepositoryInterface $stateRepo
	 * @param OrderRepositoryInterface $orderRepo
	 * @param UserQueue $userQueue
	 * @param EntityTypeRepositoryInterface $typeRepo
	 * @param EntityRepositoryInterface $entityRepo
	 */
	public function __construct(
		UserRepositoryInterface $userRepo,
		EavManager $manager,
		StateRepositoryInterface $stateRepo,
		OrderRepositoryInterface $orderRepo,
		UserQueue $userQueue,
		EntityTypeRepositoryInterface $typeRepo,
		EntityRepositoryInterface $entityRepo
	)
	{
		$this->userRepo = $userRepo;
		$this->manager = $manager;
		$this->orderRepo = $orderRepo;
		$this->stateRepo = $stateRepo;
		$this->userQueue = $userQueue;
		$this->typeRepo = $typeRepo;
		$this->entityRepo = $entityRepo;
	}

	/**
	 * Sets the user that dashboard will be generated based on
	 *
	 * @param User $user
	 */
	public function setUser(User $user)
	{
		$this->user = $user;
	}

	/**
	 * The final function that is called from outside
	 *
	 * @return array
	 */
	public function getHisDash(){
		$userQueue = $this->userQueue();
		$generatedUsers = $this->generatedUsers();
		$generatedOrders = $this->generatedOrders();
		$hisSales = $this->hisSales();
		$allOrders = $this->allOrders();
		$openOrders = $this->openOrders();
		$orderChart = $this->orderChart();
		return compact(
			'userQueue',
			'generatedOrders',
			'generatedUsers',
			'hisSales',
			'allOrders',
			'openOrders',
			'orderChart'
		);

	}

	/**
	 * Get user job queue
	 *
	 * @return mixed
	 */
	protected function userQueue()
	{
		$this->userQueue->setUser($this->user);
		return $this->userQueue->summary();
	}

	/**
	 * Get the users that user has created them
	 *
	 * @return Collection
	 */
	protected function generatedUsers()
	{
		return $this->userRepo->getGeneratedUsers($this->user,5);
	}

	/**
	 * Orders Generated by current user
	 *
	 * @return Collection
	 */
	protected function generatedOrders()
	{
		return $this->orderRepo->getGeneratedOrders($this->user, 5);
	}

	/**
	 * Get Final sales of current user
	 *
	 * @return collection
	 */
	protected function hisSales()
	{

	}

	/**
	 * A summary of all orders
	 *
	 * @return Collection
	 */
	protected function allOrders()
	{

	}

	/**
	 * A summary of open orders that are currently on progress
	 *
	 * @return Collection
	 */
	protected function openOrders()
	{

	}

	/**
	 * Provide Chart data
	 *
	 * @return array
	 */
	protected function orderChart()
	{
		$counts =  $this->orderRepo->countableMonthChart()->lists('countable','month');
		$output = [];
		$months = Config::get('jalali_months');
		foreach($months as $key => $month)
		{
			$tmpOutput['date'] = $month;
			$tmpOutput['orders'] = ! empty($counts[$key]) ? $counts[$key] : 0;
			$output[] = $tmpOutput;
		}
		return $output;
	}


}